services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Sigmapix\ProcessEventBundle\:
        resource: '../../*'
        exclude: '../../{Admin,Entity,Process,Repository,Tests}'
